<?xml version="1.0" encoding="utf-8"?>
<!-- template.xml file -->
<!-- Student = Patrick Holt -->
<!-- Created = 02/08/2022 -->
<!-- Last Edited = 28/08/2022 -->

<!DOCTYPE products [
	<!ELEMENT product (productName, description, developer?, rentalCost, searchTags*, parentalRating?, productCondition?, extra+, review*, image+, webpage, currentRenter?)>
		<!ELEMENT productName (pName, delivery) #REQUIRED> 
			<!ELEMENT pName (#CDATA) #REQUIRED> <!--Names may contain symbols so #CDATA is appropriate -->
				<!ATTLIST pName productID PCDATA #REQUIRED><!--Must produce productIDs for all products to help them have an effective primary key (even if multiple of same product) -->
			<!ELEMENT delivery (physical | digital)> <!--Must choose physical or digital-->
				<!ELEMENT physical (#CDATA)> <!--Physical may contain symbols so #CDATA is appropriate (CD & Case, DVD & Case, etc.) -->
				<!ELEMENT digital (#PCDATA)> <!--Can be in-browser streaming or digital key -->
					<!ATTLIST digital digitalKey PCDATA> <!--Digital keys shouldn't contain symbols so #PCDATA is appropriate, they may also not be required if weebsite provides this service -->
		<!ELEMENT description (#CDATA)> <!--Description may contain symbols so #CDATA is appropriate-->
		<!ELEMENT developer (#CDATA)> <!-- Developer may contain & symbol so #CDATA is appropriate--> 
		<!ELEMENT rentalCost (#CDATA)> <!--rental cost will contain symbols so #CDATA is appropriate-->
		<!ELEMENT searchTags (#PCDATA)> <!-- Tags shouldn't have symbols-->
		<!ELEMENT parentalRating (#PCDATA)> <!--Parental ratings shouldn't have symbols-->
		<!ELEMENT productCondition (#CDATA)> <!--Product condition may contain symbols depending on damage-->
		<!ELEMENT extra (name, additionalCost?)> <!--Can contain insurance, and other items-->
			<!ELEMENT name (#CDATA)> <!---Names may contain symbols so #CDATA is appropriate -->
			<!ELEMENT additionalCost (#CDATA)> <!---Additional cost may contain symbols so #CDATA is appropriate -->
		<!ELEMENT review (#CDATA)> <!--Review may contain symbols so #CDATA is appropriate-->
			<!ATTLIST review byName CDATA> <!--byName may contain symbols so #CDATA is appropriate (company reviews)-->
		<!ELEMENT image EMPTY> <!--relative path-->
			<!ATTLIST image source CDATA #REQURIED> <!--source may contain symbols so #CDATA is appropriate (company reviews)-->
			<!ATTLIST image height CDATA #REQUIRED> <!--height may contain symbols so #CDATA is appropriate (company reviews)-->
			<!ATTLIST image width CDATA #REQUIRED> <!--width may contain symbols so #CDATA is appropriate (company reviews)-->
		<!ELEMENT webpage EMPTY> <!--absolute path-->
			<!ATTLIST webpage url CDATA #REQUIRED> <!--byName may contain symbols so #CDATA is appropriate (company reviews)-->
		<!ELEMENT currentRenter (currentRenterName, currentRenterMobile+)> <!--Allow knowledge of who is currently renting item-->
			<!ELEMENT currentRenterName (#PCDATA)>  <!--renter name shouldn't contain symbols so #PCDATA is appropriat -->
				<!ATTLIST currentRenterName currentRenterID PCDATA> <!--renter ID shouldn't contain symbols so #PCDATA is appropriat -->
			<!ELEMENT currentRenterMobile (#PCDATA) > <!--mobile shouldn't contain symbols so #PCDATA is appropriat -->
	<!ENTITY badCondition "Used">
	<!ENTITY goodCondition "New">
]>

<product>
	<productName>
		<pName productID="000000">Name</pName>
		<delivery>
			<physical></physical>
		</delivery>
	</productName>
	<description></description>
	<rentalCost></rentalCost>
	<extra>
		<name></name>
		<additionalCost></additionalCost>
	</extra>
	<image source="/images/" height="0" width="0"/>
	<webpage url="index.html">
</product>